#!/usr/bin/env python3

import getopt
import sys

AUTHOR_MAP = {
}

COUNTS = {}

POS = None

def usage(f=sys.stderr):
    sys.stdout.write("""\
Usage: %s POS [FILENAME...]

Outputs counts of authors for words appearing at a given metrical
position POS. POS is a string like "2.5" or "6".

Use "." for POS to get a total of counts in any position.
""" % sys.argv[0])

def process(f):
    for line in f:
        try:
            title, lineno, positions, _, _ = line.strip().split("\t")
        except ValueError:
            raise ValueError("cannot parse line %r" % line)
        positions = set(positions.split("/"))
        author = AUTHOR_MAP.get(title, title+"?")
        if POS == "." or POS in positions:
            COUNTS.setdefault(author, 0)
            COUNTS[author] += 1

opts, args = getopt.gnu_getopt(sys.argv[1:], "h", ["help"])
for o, a in opts:
    if o == "-h" or o == "--help":
        usage()
        sys.exit()

try:
    POS, filenames = args[0], args[1:]
except IndexError:
    usage(sys.stderr)
    sys.exit(1)

if filenames:
    for filename in filenames:
        with open(filename) as f:
            process(f)
else:
    process(sys.stdin)

for author, count in sorted(COUNTS.items(), key=lambda x: x[1]):
    print("\t".join([author, str(count)]))
