#!/usr/bin/env python3

import csv
import getopt
import re
import subprocess
import sys

def usage(f=sys.stdout):
    f.write("""\
Usage: %s [<LINENO><WORD>.html]...
""")

WORKS = (
    "Il.",
    "Od.",
    "Hymns",
    "Theog.",
    "WD",
    "Shield",
    "Fr.",
    "Ap.Rh.",
    "Theoc.",
    "Call.",
    "Aratus",
)

csv_writer = csv.DictWriter(sys.stdout, fieldnames=(
    "Line #",
    "Word",
    "TLG search",
    "Sedes",
    "Total (Diogenes)",
    "Il.",
    "Od.",
    "Hymns",
    "Theog.",
    "WD",
    "Shield",
    "Fr.",
    "Ap.Rh.",
    "Theoc.",
    "Call.",
    "Aratus",
    "Notes",
    "Fixed for '?'",
))

def metricalposition(filename):
    p = subprocess.Popen(["./metricalposition", filename], stdout=subprocess.PIPE)
    return p.stdout

def process(filename):
    m = re.match(r'^(\d+)(.+)\.html$', filename)
    line_num = int(m.group(1))
    word = m.group(2)
    row = {
        "Line #": line_num,
        "Word": word,
        "Fixed for '?'": "Yes",
    }
    for work in WORKS:
        row.setdefault(work, 0)

    possible_sedes = set()

    position_counts = {}
    total_counts = {}
    for line in metricalposition(filename):
        work, lineno, positions, _, _ = line.decode("utf-8").strip().split("\t")
        positions = set(positions.split("/"))
        total_counts.setdefault(work, 0)
        total_counts[work] += 1
        for pos in positions:
            if pos == "?":
                row["Fixed for '?'"] = "No"
            position_counts.setdefault(pos, {})
            position_counts[pos].setdefault(work, 0)
            position_counts[pos][work] += 1

            if work == "Shield" and lineno == str(line_num):
                possible_sedes.add(pos)

    if len(possible_sedes) == 1:
        sedes = possible_sedes.pop()
        row["Sedes"] = sedes
        for work, count in position_counts[sedes].items():
            row[work] = count

    csv_writer.writerow(row)

opts, filenames = getopt.gnu_getopt(sys.argv[1:], "-h", ["help"])
for o, a in opts:
    if o == "-h" or o == "--help":
        usage()
        sys.exit()

csv_writer.writeheader()

for filename in filenames:
    process(filename)
