#!/usr/bin/env python3

# Outputs a CSV of each word in each line.
# Usage: ./wordlist corpus/shield.txt > shield-wordlist.csv

import csv
import getopt
import sys

csv_writer = csv.DictWriter(sys.stdout, fieldnames=("Line #", "Word"))

def strip(word):
    return word.strip(".,·[]“”")

def process(f):
    line_num = 0
    for line in f:
        line_num += 1
        for word in line.split():
            csv_writer.writerow({"Line #": line_num, "Word": strip(word)})

def process_filename(filename):
    with open(filename) as f:
        return process(f)

csv_writer.writeheader()

_, filenames = getopt.gnu_getopt(sys.argv[1:], "")
for filename in filenames:
    process_filename(filename)
