#!/usr/bin/env python3

# Displays lines that do not have a unique scansion.
#
# Usage:
#   nonunique-scansion FILENAME.xml
# FILENAME.xml is the name of the XML document containing the text of the work.

import getopt
import re
import sys

import sedes
import tei

def usage(file=sys.stdout):
    print("""\
Usage: {} IDENTIFIER FILENAME.xml

IDENTIFIER is a short text identifier for the work; e.g., "Il.".
FILENAME.XML is a TEI XML document containing the text of the work.
""".format(sys.argv[0]), end="", file=file)

def process(f):
    global work_identifier
    doc = tei.TEI(f)
    for line in doc.lines():
        assignments = sedes.analyze(line.text)
        if len(assignments) == 1:
            continue

        print()
        print("    {!r}: # {} {}.{}".format(line.text, work_identifier, line.book_n, line.line_n))
        for assignment in assignments:
            print("        {},".format(tuple((word, shape) for (word, _, shape) in assignment)))

opts, args = getopt.gnu_getopt(sys.argv[1:], "h", ["help"])
for o, a in opts:
    if o in ("-h", "--help"):
        usage()
        sys.exit(0)

try:
    work_identifier, input_filename = args
except ValueError:
    print("error: usage error", file=sys.stderr)
    print(file=sys.stderr)
    usage(sys.stderr)
    sys.exit(1)

with open(input_filename) as f:
    process(f)
